### ISSUE TITLE
"Stop" button crashes the interpreter

### ISSUE THREAD

**Issue by mnalis** [inexorabletash/jslogo#124]
for example, paste the code:

`cs ct print "Start while [ 1 = 1] [ print random 100 ]`

and click `Run` button. It will start printing random numbers, and button will change to `Stop`. Upon pressing the `Stop`, the code will stop executing, but trying to run anything else will simply execute nothing. For example, trying

`cs ct pr "Hello` 

will not clear the screen nor change anything displayed on it, but the button will change from "Run" to "Stop" and remain in "Stop" until it is clicked again. Only way to make JSLogo start executing commands again is to refresh the browser window.

**Comment by mnalis** [comment]
Tried it in both Firefox 68.4.1esr and Chromium 79.0.3945.130 (Debian Buster GNU/Linux); fails the same both at my local instance and at https://www.calormen.com/jslogo/

**Comment by inexorabletash** [comment]
Same as the other bug, probably a place where a promise rejection is not being propagated out or handled correctly, a bug likely introduced when the execution was made async. 

I'll try and track this down soon.

**Comment by inexorabletash** [comment]
This was a bug in `WHILE` where termination wasn't handled. Thanks for the report!
