### ISSUE TITLE
Suggestion: query to find the screen size (or if position is onscreen/offscreen)

### ISSUE THREAD

**Issue by gwhitney** [inexorabletash/jslogo#141]
I did check and I realize this would be an extension to the UCB Logo you reference, but I was making some spirals that were going offscreen and I wanted to autoscale as the turtle's path grew. I see there is a setscrunch which would let me scale the coordinates, but I couldn't see any predicate that would let me tell when I needed to do this (i.e, when the turtle had gone off screen), or function to find the screen dimensions. Adding one or both would be helpful for this sort of thing.

**Comment by bojidar-bg** [comment]
Technically, one can use the `pos`/`xcor`/`ycor` commands to figure the screensize; but it is a bit.. hacky.

For example:
```logo
TO screensize
  localmake "pd pendownp
  penup
  localmake "mode turtlemode
  fence
  localmake "pos pos
  localmake "heading heading
  home

  fd 10000000 rt 90 fd 10000000
  localmake "size (list xcor * 2 ycor * 2) 

  apply :mode [] ; turtlemode just so happens to return the exact names of the procedures for switching back to the mode
  setpos :pos
  seth :heading
  if :pd [ pendown ]

  output :size
END
```

**Comment by gwhitney** [comment]
Thanks. I didn't think of bashing the poor turtle's head into the corner of the fence!

**Comment by inexorabletash** [comment]
Adding a proc to return the size sounds good to me. Suggestions for name (`SCREENSIZE` ?) and what it should return?  A two member list with the width and height like the example given by @bojidar-bg seems fine. Alternately it could return return the coordinates of the screen corners, but that since the viewport is always centered on 0,0 that can be calculated, and we can add that if we ever support translation.

**Comment by gwhitney** [comment]
Anything reasonable is fine with me, but since the viewport will presumably always be a "rect", a list "(xmin xmax ymin ymax)" might be the most future-proof. Just two cents.

**Comment by inexorabletash** [comment]
How about scrunch? Should the bounds be scaled by the current scrunch factor? (IMHO: yes)

**Comment by inexorabletash** [comment]
Okay, in there as `BOUNDS`

**Comment by gwhitney** [comment]
Wow, that was crazy fast and it's already in the online interpreter. Nice!
(Of course, then when I tried to use it to scale my spirals down as the turtle went off the screen, I discovered that scrunching, counterintuitively to me, did not scale the things that had already been drawn. All that "ink" just stays where it was on the screen. So making the scale just adapt as the turtle goes outside the window is not as easy as I thought -- I thought I could just make a replacement for forward, say scalingForward, that did the forward then scaled to get the turtle back on screen if need be. But it doesn't matter how much you scale -- the turtle stays off screen. So instead of being able to just "patch" the forward function, I'd have to detect the out of scale and restart the whole drawing from the beginning at the smaller scale. That's a much bigger project...)

**Comment by bojidar-bg** [comment]
IIRC some logos had functions for copying and pasting images from the canvas (E.g. FMSLogo has [BITCUT](https://fmslogo.sourceforge.io/manual/command-bitcut.html)/[BITPASTE](https://fmslogo.sourceforge.io/manual/command-bitpaste.html), TerrapinLogo has [SNAP](https://resources.terrapinlogo.com/weblogo/commands/shapes#snap)/[STAMP](https://resources.terrapinlogo.com/weblogo/commands/shapes#stamp), and HTML5 canvas context has [getImageData](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/getImageData)/[putImageData](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/putImageData)), but... indeed, supporting that does feel like a much larger project.

**Comment by inexorabletash** [comment]
That would be pretty easy - it's basically just translating calls into get/putImageData. Writing good tests will be the hardest part. Want to give it a try?On Sep 15, 2023, at 11:47 PM, Bojidar Marinov ***@***.***> wrote:﻿
IIRC some logos had functions for copying and pasting images from the canvas (E.g. FMSLogo has BITCUT/BITPASTE, TerrapinLogo has SNAP/STAMP, and HTML5 canvas context has getImageData/putImageData), but... indeed, supporting that does feel like a much larger project.

**Comment by gwhitney** [comment]
Well I have to say my presumption was if they turtle was at coordinate 500, 300 just offscreen, and I did a `setscrunch 0.5 0.5` then the turtle would still be at 500, 300 and now be on screen. Instead, the turtle is now at 1000, 600 -- at the same "physical" location that it was. That seems very counterintuitive, and not something addressed by something like "snap/stamp".

**Comment by inexorabletash** [comment]
@gwhitney - it sounds like you're reporting a new issue, whereas @bojidar-bg was suggesting a new feature.

**Comment by inexorabletash** [comment]
And regarding the turtle coordinates before/after `SETSCRUNCH` - I appear to have explicit code to preserve the turtle's physical location even when the scaling changes (as part of a fix for #95), so that behavior is intentional. Consider doing `MAKE "p POS` before `SETSCRUNCH` and `SETPOS :p` after, I guess.

**Comment by gwhitney** [comment]
Well, not sure. I was just discussing the fact that the turtle's _coordinates_ change based on scaling the screen as really counterintuitive. I understand that it is the intention, it just seems like a choice that's a little tricky to work with. And it's not just the turtle -- if I have drawn a square that appears to be 10 cm on a side on my screen, after a `setscrunch 0.5 0.5` it still appears to be 10 cm on a side on my screen -- in other words, the coordinates of the black pixels have changed, rather than their physical locations. Again, I presume that's intentional; but it's conceptually a tricky model of what's going on, at least for me to work with mentally. And practically speaking, it makes it difficult to rescale an existing drawing. You have to clear and redraw everything, or possibly the feature bojidar-bg is suggesting would help, as long as there is some way to scale the result of a "snap" before "stamp"ing it. In any case, it becomes a big project to autoscale a drawing out if it goes offscreen. That's all. Thanks so much for providing jslogo on line for free! I am very appreciative.

**Comment by bojidar-bg** [comment]
The problem with redrawing everything is that it would require memorizing all segments drawn so far — which is great for mathy visualizations where the number of objects on the screen is relatively small, but quickly gets out of hand for complex artworks. I vaguely recall there being another implementation of Logo in JavaScript which used SVG and would conceptually allow for that with minimal code changes. I can't find it right now tho; but from what I remember, it did get slower the more things there were on-screen.

@inexorabletash I'll open a new issue for the Snap/Stamp feature, as I would be interested in seeing support for that regardless of where the discussion here goes :sweat_smile:
