### ISSUE TITLE
Problem: i18n: translate Logo's command to Polish

### ISSUE THREAD

**Issue by nitro2010** [inexorabletash/jslogo#33]
Hello,

I want translate Logo's command to Polish language in JsLogo, but I have problem with Polish characters ( ążćńół ), example forward in Polish means naprzód. I replace forward in jslogo and I get error that this command is incorrect in jslogo. I'm afraid that it's caused by the fact that JavaScript encodes incorrectly characters.

Is way to fix it?

Thanks

**Comment by nitro2010** [comment]
Yeah! Success! I translate in 100% JSLOGO to Polish lang!

http://nitro2010.github.io/jslogo/

I'm will publish code and documentation.

I have one small problem.
In cm/logo.js I have translate words: TO and END to OTO and JUŻ, but it doesn't color "JUŻ" in input statements. JavaScript String Escape doesn't work.

**Comment by inexorabletash** [comment]
Try writing it as `/JU\u017b/`

**Comment by nitro2010** [comment]
hmmm... I replace:
/^END\b/i
to:
/^JU\u017B/i
[Escape string and remove \b]
and it's working...

**Comment by inexorabletash** [comment]
You probably want the \b at the end too. Does it work with that?

**Comment by nitro2010** [comment]
No, it doesn't work

**Comment by inexorabletash** [comment]
Okay. Yeah, \b only matched "word" boundaries where word characters are [A-Za-z0-9_] so it won't work with non-ASCII characters in the match expression.

If it is a common prefix we can probably come up with a better negative lookahead assertion.

**Comment by nitro2010** [comment]
I think so, european and russian chars no match in [A-Za-z0-9_], but It working.

Uh, I'm so very happy. Later, I will play with jquery, and others :)
