### ISSUE TITLE
any simple way to embed and use it?

### ISSUE THREAD

**Issue by ctzurcanu** [inexorabletash/jslogo#38]
If one would like to just use the logo scripts without other integration like togetherjs or codemirror, how does one do that without reverse-engineering a good chunk of your code?
Example pls.

**Comment by inexorabletash** [comment]
You can look at `m.htm` for a more minimal example that doesn't use any of those extras. The history code could be removed, of course.

**Comment by ctzurcanu** [comment]
yes! after excluding history, works nicely. is `stream` variable needed?

**Comment by inexorabletash** [comment]
Yes, `stream` is needed, although the functions can be no-ops. They represent writing to the text display (e.g. `PRINT "Hello`). If that's not necessary to support you can simplify it.
