### ISSUE TITLE
Route def() through localization hook

### ISSUE THREAD

**Issue by inexorabletash** [inexorabletash/jslogo#43]
Basically, have `def(name, func)` pass `name` through `__()`

**Comment by alonbl** [comment]
I would like to avoid this, see[1], there should be multiple aliases per command, we should keep the english and add alternate aliases. Alias can be alias in english a already implemented or localization aliases.

In principal, even if localized we should able to run standard logo program.

[1] https://github.com/alonbl/jslogo/commit/36a988523b273a1e5ef86cd522e182e731bce861

**Comment by inexorabletash** [comment]
Good point.

I think at some point in the past I suggested an aliasing mechanism to someone, possibly just executing a series of `copydef` commands.
