### ISSUE TITLE
Expose localization hook

### ISSUE THREAD

**Issue by inexorabletash** [inexorabletash/jslogo#44]
Allow assigning `localize` property to `LogoInterpreter` instance, call it from `__()` if set.

**Comment by alonbl** [comment]
I would like to be able multiple languages, so please support lists.

I will use whatever mechanism you apply, but please support multiple option for each atom.

**Comment by alonbl** [comment]
See [1] for temporary usage.

[1] https://github.com/alonbl/jslogo/blob/36a988523b273a1e5ef86cd522e182e731bce861/translation.he.js

**Comment by inexorabletash** [comment]
The translation function in your example makes complete sense and is what I was expecting. 

Can you give me an example of "multiple option for each atom" ? I think I'm misunderstanding.

**Comment by alonbl** [comment]
let's first begin with command aliases.

what I had in mind are the following changes:

1. modify the "Procedures and Flow Control" section, each def() will have only one name, which probably be the long most complete one.

2. add defAliases(name, aliases) method, or even better if you like metadata programming have it as defAlias(aliases) which is dictionary of lists.

3. call defAliases at constructor to register language aliases.

4. at localization it is possible to call defAliases to register even more, without modifying the core.

```javascript
logo.defAliases({
    "command1": ["alias11", "alias12"],
    "command2": ["alias21", "alias22"]
});
```

**Comment by inexorabletash** [comment]
So we're talking about several different things here:

* Localizations on output; this is what the `__()` function hook would do.
* Procedure aliases. There's no need for the API to support lists, you can just have multiple mappings. Under the hood this can just do the same thing as `copydef`. In your example:
```
copydef "alias11 "command1
copydef "alias12 "command1
copydef "alias21 "command2
copydef "alias22 "command2
```
I'm not opposed to exposing e.g. `copydef()` on the interpreter object that does this.

Color names (which are HTML constants, not anything associated with Logo) can be handled at the turtle level, e.g. a translation function called whenever `canvas_ctx.fillStyle` or `canvas_ctx.strokeStyle` is being set.

Are there other inputs or outputs that need handling?

**Comment by inexorabletash** [comment]
The plumbing should be in place for these now. Let me know if these make sense.
