### ISSUE TITLE
Make the turtle look like a turtle

### ISSUE THREAD

**Issue by inexorabletash** [inexorabletash/jslogo#56]
While I personally appreciate the "spaceship from Asteroids" aesthetic, making the turtle look like a turtle might be more appealing for kids.

Most implementations seem to use an opaque box turtle - very round shell with stubby limbs, head and tail. I think this would make it difficult to distinguish the orientation and the position of the pen. Also, box turtles are slow and boring.

So how about a stylized outline of a sea turtle?  Sea turtles are aerodynamic and cool.

Something like this but just an outline: http://www.clker.com/clipart-turtle-outline-3.html

**Comment by alonbl** [comment]
I liked the old classic turtle... :)
