### ISSUE TITLE
Maximum call stack size exceeded in Chrome

### ISSUE THREAD

**Issue by ajcyeh** [inexorabletash/jslogo#82]
This seems to be a Chrome issue. I am using the latest Chrome Version 51.0.2704.63 (64-bit) on Macbook Pro. Just running the second example 

TO square :length
  repeat 4 [ fd :length rt 90 ]
END
TO randomcolor
  setcolor pick [ red orange yellow green blue violet ]
END
clearscreen
repeat 36 [ randomcolor square random 200 rt 10 ]

will get a "Maximum call stack size exceeded" message. This does not reproduce in FireFox.

**Comment by inexorabletash** [comment]
Thanks for the report!

I've filed https://crbug.com/615485 against Chrome as there is an unexpected (?) behavior change there. But it also looks like a lurking bug in jslogo that I will fix later today: if `to_arity()` is called with a function named `func` the generated function will recurse and cause the exception when called.

**Comment by ajcyeh** [comment]
Thanks for the quick reply. Hope this can be resolved soon. :-)
