### ISSUE TITLE
MAP with multiple inputs does not work

### ISSUE THREAD

**Issue by ajcyeh** [inexorabletash/jslogo#84]
http://people.eecs.berkeley.edu/~bh/v1ch5/hof.html

show (map "sum [1 2 3] [40 50 60] [700 800 900]) should output [741 852 963] but instead in jslogo it outputs [1 2 3].

**Comment by inexorabletash** [comment]
Fixed, thanks!

**Comment by ajcyeh** [comment]
Thank you. :-)
