### ISSUE TITLE
strange behaviour of repcount

### ISSUE THREAD

**Issue by ajcyeh** [inexorabletash/jslogo#85]
This will produce an error:
repeat 10 [
  print 100 ^ (repcount/10)
]

This will be fine:
repeat 10 [
  print 100 ^ ((repcount)/10)
]

Is this part of the Logo syntax of a bug?

**Comment by inexorabletash** [comment]
Minimized repro:
```
print (xcor / 1)
```
It's seeing '(' 'xcor' and falling into Lisp-style call syntax, so trying to evaluate '/ 1' to produce an argument. I'm not sure what UCBLogo does here - will check.

**Comment by inexorabletash** [comment]
Added a special case in the parser:

`'(' word ...` is a parenthesized call expression unless it's `'(' word infix-operator ...`
