### ISSUE TITLE
forever should yield so UI remains responsive

### ISSUE THREAD

**Issue by ajcyeh** [inexorabletash/jslogo#86]
The use of forever statement can easily cause a forever loop to crash the browser. Is it possible to perhaps automatically insert a "wait 0" or the wait effect so the stop button will work? 

For example, this will crash the browser:
forever [
  print 100 ^ ((repcount)/10)
]
And this will be fine:
forever [
  print 100 ^ ((repcount)/10)
  wait 0
]

**Comment by inexorabletash** [comment]
Hopefully that should be easy to add. We could potentially sprinkle "yields" into other looping/recursion places too.

**Comment by ajcyeh** [comment]
That will be great. Things like long repeat/recursion can also stop the UI from responding.
