### ISSUE TITLE
Make stream.read async, don't use window.prompt

### ISSUE THREAD

**Issue by inexorabletash** [inexorabletash/jslogo#94]

**Comment by yamboy1** [comment]
Could you elaborate on this.

**Comment by inexorabletash** [comment]
Making `stream.read` async is really simple - should just be a few minutes of work. It's replacing `prompt()` that'll be somewhat time consuming since I don't want to pull in a dependency on any JS UI libraries.

**Comment by inexorabletash** [comment]
For the first part, callers of stream.read in logo.js need to handle promises and the implementations of read() in index.js and the tests should return promises.

**Comment by inexorabletash** [comment]
I made the async change. The remaining work is to replace `window.prompt()` with custom UI.
